export const ROCK = 'ROCK';
export const SCISSORS = 'SCISSORS';
export const PAPER = 'PAPER';
export const MOVES = [ROCK, SCISSORS, PAPER];
export const DRAW_TEXT = "It's a draw";
export const PLAYER_1 = 'PLAYER_1';
export const PLAYER_2 = 'PLAYER_2'
export const PLAYER_1_WINS_TEXT = 'Player 1 wins';
export const PLAYER_2_WINS_TEXT = 'Player 2 wins';
